# .pre-commit-config.yaml
# Add tail-chasing detection to your pre-commit hooks

repos:
  - repo: local
    hooks:
      - id: tail-chasing
        name: Tail-Chasing Detection
        entry: tailchasing
        language: system
        types: [python]
        pass_filenames: false
        args: [
          "--fail-on", "20",  # Fail if score > 20
          "--incremental",    # Only analyze changed files
          "--quiet"           # Less verbose output
        ]
        
      - id: semantic-duplicates
        name: Semantic Duplicate Check
        entry: tailchasing
        language: system
        types: [python]
        pass_filenames: true
        args: [
          "--only", "semantic_duplicate_function",
          "--min-severity", "3"
        ]