# Example configuration for ChromatinContactAnalyzer
# This shows how to enable and configure chromatin contact analysis

# Enable chromatin contact analysis
chromatin_contact:
  enabled: true
  
  # Distance metric weights (should sum to ~1.0)
  weights:
    token: 0.3      # Token/line distance weight
    ast: 0.25       # AST tree distance weight  
    module: 0.25    # Module/import distance weight
    git: 0.2        # Git co-edit correlation weight
  
  # Contact probability parameters
  contact_params:
    kappa: 1.0        # Contact strength constant
    alpha: 1.5        # Power law exponent
    epsilon: 0.1      # Regularization parameter
    tad_penalty: 0.7  # Penalty for cross-compartment contacts
  
  # Detection thresholds
  contact_threshold: 0.3    # Minimum contact probability to report
  thrash_threshold: 0.2     # Minimum thrash risk to report

# You can combine with other analyzers
context_thrashing:
  enabled: true
  similarity_threshold: 0.7
  min_line_distance: 50

# Phantom stub analysis
placeholders:
  triage_enabled: true
  
# Example usage:
# tailchasing-enhanced . --config .tailchasing.chromatin.yml